### ISSUE TITLE
"Invalid result value" error when trying to install versions of Deno beyond v0.35.0

### ISSUE THREAD

**Issue by MasterKale** [imbsky/dvm#1]
dvm v1.1.0 is unable to download any version of Deno after v0.35.0:

```sh
$> dvm --version
1.1.0
$> dvm install 1.0.0
dvm: internal error, uncaught exception:
     (Failure "Invalid result value")
     Raised at file "stdlib.ml", line 29, characters 17-33
     Called from file "src/install.re" (inlined), line 31, characters 16-48
     Called from file "src/install.re", line 57, characters 10-67
     Called from file "cmdliner_term.ml", line 25, characters 19-24
     Called from file "cmdliner.ml", line 117, characters 32-39
```

The culprit seems to be [this pattern](https://github.com/imbsky/dvm/blob/master/src/install.re#L3) used to construct the download URL from the version provided to `dvm install`:

```
https://github.com/denoland/deno/releases/download/v%s/deno_%s_%s.gz
```

Deno v0.35.0 was the last release to use this naming convention. The latest releases use the following naming scheme, including today's v1.0.0 release:

<img width="795" alt="Screen Shot 2020-05-13 at 4 48 15 PM" src="https://user-images.githubusercontent.com/5166470/81877321-96914a00-9539-11ea-874c-5f71a5f9657e.png">

**Comment by MasterKale** [comment]
I neglected to include a download URL, here's one for the macOS release of Deno 1.0.0 pulled from https://github.com/denoland/deno/releases/tag/v1.0.0:

```
https://github.com/denoland/deno/releases/download/v1.0.0/deno-x86_64-apple-darwin.zip
```

**Comment by imbsky** [comment]
Yeah, you're right. I've been aware of the problem for quite some time and already fixed for asdf-deno, but no fixes have been made for this. I would like to rewrite all of this in the near future, but I don't have enough bandwidth right now so ETA don't exist. But Deno v1.0.0 has been released, so I want to fix it as soon as possible.

**Comment by imbsky** [comment]
If you want to do version control right now, asdf-deno is the best option. https://github.com/asdf-community/asdf-deno

**Comment by imbsky** [comment]
My friend seems to be working on this issue. It will be fixed soon.

**Comment by imbsky** [comment]
This problem has been fixed by @Haritaso, thanks! FYI: @MasterKale
